# Generated by Django 4.0.5 on 2022-06-20 21:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bounty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField(max_length=1000)),
                ('reward', models.PositiveSmallIntegerField()),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddConstraint(
            model_name='bounty',
            constraint=models.CheckConstraint(check=models.Q(('reward__range', (1, 500))), name='reward_range'),
        ),
    ]
