# Generated by Django 4.0.5 on 2022-06-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bounties', '0005_alter_bounty_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Ongoing'), (1, 'Awarded'), (2, 'Expired'), (3, 'Deleted')], default=0),
        ),
    ]
