# Generated by Django 4.0.5 on 2022-06-28 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bounties', '0006_bounty_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bounty',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bounties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Awarded'), (1, 'Unawarded')], default=1)),
                ('text', models.CharField(max_length=1000)),
                ('bounty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='bounties.bounty')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='solutions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
