# Generated by Django 4.0.5 on 2022-06-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bounties', '0007_alter_bounty_creator_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Awarded'), (1, 'Unawarded'), (2, 'Deleted')], default=1),
        ),
    ]
